/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TRANSPORTER_TRANSPORTER_PB_H_INCLUDED
#define PB_TRANSPORTER_TRANSPORTER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _transporter_UID {
    pb_callback_t value;
} transporter_UID;

typedef struct _transporter_RegisterRequest {
    pb_callback_t id;
} transporter_RegisterRequest;

typedef struct _transporter_RegisterResponse {
    pb_callback_t id;
    bool has_uid;
    transporter_UID uid;
} transporter_RegisterResponse;

typedef struct _transporter_RevokeRequest {
    bool has_uid;
    transporter_UID uid;
} transporter_RevokeRequest;

typedef struct _transporter_RfidEnvelope {
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        transporter_RegisterRequest register_request;
        transporter_RegisterResponse register_response;
        transporter_RevokeRequest revoke_request;
    } payload;
} transporter_RfidEnvelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define transporter_UID_init_default             {{{NULL}, NULL}}
#define transporter_RegisterRequest_init_default {{{NULL}, NULL}}
#define transporter_RegisterResponse_init_default {{{NULL}, NULL}, false, transporter_UID_init_default}
#define transporter_RevokeRequest_init_default   {false, transporter_UID_init_default}
#define transporter_RfidEnvelope_init_default    {{{NULL}, NULL}, 0, {transporter_RegisterRequest_init_default}}
#define transporter_UID_init_zero                {{{NULL}, NULL}}
#define transporter_RegisterRequest_init_zero    {{{NULL}, NULL}}
#define transporter_RegisterResponse_init_zero   {{{NULL}, NULL}, false, transporter_UID_init_zero}
#define transporter_RevokeRequest_init_zero      {false, transporter_UID_init_zero}
#define transporter_RfidEnvelope_init_zero       {{{NULL}, NULL}, 0, {transporter_RegisterRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define transporter_UID_value_tag                1
#define transporter_RegisterRequest_id_tag       1
#define transporter_RegisterResponse_id_tag      1
#define transporter_RegisterResponse_uid_tag     2
#define transporter_RevokeRequest_uid_tag        1
#define transporter_RfidEnvelope_register_request_tag 3
#define transporter_RfidEnvelope_register_response_tag 4
#define transporter_RfidEnvelope_revoke_request_tag 5

/* Struct field encoding specification for nanopb */
#define transporter_UID_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             1)
#define transporter_UID_CALLBACK pb_default_field_callback
#define transporter_UID_DEFAULT NULL

#define transporter_RegisterRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1)
#define transporter_RegisterRequest_CALLBACK pb_default_field_callback
#define transporter_RegisterRequest_DEFAULT NULL

#define transporter_RegisterResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uid,               2)
#define transporter_RegisterResponse_CALLBACK pb_default_field_callback
#define transporter_RegisterResponse_DEFAULT NULL
#define transporter_RegisterResponse_uid_MSGTYPE transporter_UID

#define transporter_RevokeRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uid,               1)
#define transporter_RevokeRequest_CALLBACK NULL
#define transporter_RevokeRequest_DEFAULT NULL
#define transporter_RevokeRequest_uid_MSGTYPE transporter_UID

#define transporter_RfidEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,register_request,payload.register_request),   3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,register_response,payload.register_response),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,revoke_request,payload.revoke_request),   5)
#define transporter_RfidEnvelope_CALLBACK NULL
#define transporter_RfidEnvelope_DEFAULT NULL
#define transporter_RfidEnvelope_payload_register_request_MSGTYPE transporter_RegisterRequest
#define transporter_RfidEnvelope_payload_register_response_MSGTYPE transporter_RegisterResponse
#define transporter_RfidEnvelope_payload_revoke_request_MSGTYPE transporter_RevokeRequest

extern const pb_msgdesc_t transporter_UID_msg;
extern const pb_msgdesc_t transporter_RegisterRequest_msg;
extern const pb_msgdesc_t transporter_RegisterResponse_msg;
extern const pb_msgdesc_t transporter_RevokeRequest_msg;
extern const pb_msgdesc_t transporter_RfidEnvelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define transporter_UID_fields &transporter_UID_msg
#define transporter_RegisterRequest_fields &transporter_RegisterRequest_msg
#define transporter_RegisterResponse_fields &transporter_RegisterResponse_msg
#define transporter_RevokeRequest_fields &transporter_RevokeRequest_msg
#define transporter_RfidEnvelope_fields &transporter_RfidEnvelope_msg

/* Maximum encoded size of messages (where known) */
/* transporter_UID_size depends on runtime parameters */
/* transporter_RegisterRequest_size depends on runtime parameters */
/* transporter_RegisterResponse_size depends on runtime parameters */
/* transporter_RevokeRequest_size depends on runtime parameters */
/* transporter_RfidEnvelope_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
