/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TRANSPORTER_TRANSPORTER_PB_H_INCLUDED
#define PB_TRANSPORTER_TRANSPORTER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _transporter_Devices {
    transporter_Devices_DEVICE_UNSPECIFIED = 0,
    transporter_Devices_DEVICE_AQI = 1,
    transporter_Devices_DEVICE_DHT22 = 2,
    transporter_Devices_DEVICE_MOTION = 3,
    transporter_Devices_DEVICE_LDR = 4
} transporter_Devices;

/* Struct definitions */
typedef struct _transporter_Timestamp {
    int64_t seconds;
    int32_t nanos;
} transporter_Timestamp;

typedef struct _transporter_Surrondings {
    pb_callback_t id;
    double aqi;
    double temperature;
    double humidity;
    pb_callback_t aqi_port;
    int32_t dht22_port;
    bool has_timestamp;
    transporter_Timestamp timestamp;
} transporter_Surrondings;

typedef struct _transporter_SurrondingsList {
    pb_callback_t surrondings;
} transporter_SurrondingsList;

typedef struct _transporter_Motion {
    pb_callback_t id;
    bool motion;
    int32_t port;
    bool has_timestamp;
    transporter_Timestamp timestamp;
} transporter_Motion;

typedef struct _transporter_MotionList {
    pb_callback_t motion;
} transporter_MotionList;

typedef struct _transporter_LDR {
    pb_callback_t id;
    double ldr;
    pb_callback_t port;
} transporter_LDR;

typedef struct _transporter_LDRList {
    pb_callback_t ldr;
} transporter_LDRList;

typedef struct _transporter_SecurityRequest {
    pb_callback_t id;
    pb_callback_t rfid;
    bool has_timestamp;
    transporter_Timestamp timestamp;
} transporter_SecurityRequest;

typedef struct _transporter_SecurityResponse {
    pb_callback_t id;
    pb_callback_t rfid;
    bool approved;
    bool has_timestamp;
    transporter_Timestamp timestamp;
} transporter_SecurityResponse;

typedef struct _transporter_Config {
    pb_callback_t id;
    pb_callback_t name;
    pb_callback_t description;
    transporter_Devices device;
    pb_callback_t port;
    int32_t pin;
    bool enabled;
    bool has_timestamp;
    transporter_Timestamp timestamp;
} transporter_Config;

typedef struct _transporter_ConfigList {
    pb_callback_t config;
} transporter_ConfigList;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _transporter_Devices_MIN transporter_Devices_DEVICE_UNSPECIFIED
#define _transporter_Devices_MAX transporter_Devices_DEVICE_LDR
#define _transporter_Devices_ARRAYSIZE ((transporter_Devices)(transporter_Devices_DEVICE_LDR+1))










#define transporter_Config_device_ENUMTYPE transporter_Devices



/* Initializer values for message structs */
#define transporter_Timestamp_init_default       {0, 0}
#define transporter_Surrondings_init_default     {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0, false, transporter_Timestamp_init_default}
#define transporter_SurrondingsList_init_default {{{NULL}, NULL}}
#define transporter_Motion_init_default          {{{NULL}, NULL}, 0, 0, false, transporter_Timestamp_init_default}
#define transporter_MotionList_init_default      {{{NULL}, NULL}}
#define transporter_LDR_init_default             {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define transporter_LDRList_init_default         {{{NULL}, NULL}}
#define transporter_SecurityRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}, false, transporter_Timestamp_init_default}
#define transporter_SecurityResponse_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, false, transporter_Timestamp_init_default}
#define transporter_Config_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _transporter_Devices_MIN, {{NULL}, NULL}, 0, 0, false, transporter_Timestamp_init_default}
#define transporter_ConfigList_init_default      {{{NULL}, NULL}}
#define transporter_Timestamp_init_zero          {0, 0}
#define transporter_Surrondings_init_zero        {{{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0, false, transporter_Timestamp_init_zero}
#define transporter_SurrondingsList_init_zero    {{{NULL}, NULL}}
#define transporter_Motion_init_zero             {{{NULL}, NULL}, 0, 0, false, transporter_Timestamp_init_zero}
#define transporter_MotionList_init_zero         {{{NULL}, NULL}}
#define transporter_LDR_init_zero                {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define transporter_LDRList_init_zero            {{{NULL}, NULL}}
#define transporter_SecurityRequest_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}, false, transporter_Timestamp_init_zero}
#define transporter_SecurityResponse_init_zero   {{{NULL}, NULL}, {{NULL}, NULL}, 0, false, transporter_Timestamp_init_zero}
#define transporter_Config_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _transporter_Devices_MIN, {{NULL}, NULL}, 0, 0, false, transporter_Timestamp_init_zero}
#define transporter_ConfigList_init_zero         {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define transporter_Timestamp_seconds_tag        1
#define transporter_Timestamp_nanos_tag          2
#define transporter_Surrondings_id_tag           1
#define transporter_Surrondings_aqi_tag          2
#define transporter_Surrondings_temperature_tag  3
#define transporter_Surrondings_humidity_tag     4
#define transporter_Surrondings_aqi_port_tag     5
#define transporter_Surrondings_dht22_port_tag   6
#define transporter_Surrondings_timestamp_tag    7
#define transporter_SurrondingsList_surrondings_tag 1
#define transporter_Motion_id_tag                1
#define transporter_Motion_motion_tag            2
#define transporter_Motion_port_tag              3
#define transporter_Motion_timestamp_tag         5
#define transporter_MotionList_motion_tag        1
#define transporter_LDR_id_tag                   1
#define transporter_LDR_ldr_tag                  2
#define transporter_LDR_port_tag                 3
#define transporter_LDRList_ldr_tag              1
#define transporter_SecurityRequest_id_tag       1
#define transporter_SecurityRequest_rfid_tag     2
#define transporter_SecurityRequest_timestamp_tag 3
#define transporter_SecurityResponse_id_tag      1
#define transporter_SecurityResponse_rfid_tag    2
#define transporter_SecurityResponse_approved_tag 3
#define transporter_SecurityResponse_timestamp_tag 4
#define transporter_Config_id_tag                1
#define transporter_Config_name_tag              2
#define transporter_Config_description_tag       3
#define transporter_Config_device_tag            4
#define transporter_Config_port_tag              5
#define transporter_Config_pin_tag               6
#define transporter_Config_enabled_tag           7
#define transporter_Config_timestamp_tag         8
#define transporter_ConfigList_config_tag        1

/* Struct field encoding specification for nanopb */
#define transporter_Timestamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    seconds,           1) \
X(a, STATIC,   SINGULAR, INT32,    nanos,             2)
#define transporter_Timestamp_CALLBACK NULL
#define transporter_Timestamp_DEFAULT NULL

#define transporter_Surrondings_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, DOUBLE,   aqi,               2) \
X(a, STATIC,   SINGULAR, DOUBLE,   temperature,       3) \
X(a, STATIC,   SINGULAR, DOUBLE,   humidity,          4) \
X(a, CALLBACK, SINGULAR, STRING,   aqi_port,          5) \
X(a, STATIC,   SINGULAR, INT32,    dht22_port,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         7)
#define transporter_Surrondings_CALLBACK pb_default_field_callback
#define transporter_Surrondings_DEFAULT NULL
#define transporter_Surrondings_timestamp_MSGTYPE transporter_Timestamp

#define transporter_SurrondingsList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  surrondings,       1)
#define transporter_SurrondingsList_CALLBACK pb_default_field_callback
#define transporter_SurrondingsList_DEFAULT NULL
#define transporter_SurrondingsList_surrondings_MSGTYPE transporter_Surrondings

#define transporter_Motion_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, BOOL,     motion,            2) \
X(a, STATIC,   SINGULAR, INT32,    port,              3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         5)
#define transporter_Motion_CALLBACK pb_default_field_callback
#define transporter_Motion_DEFAULT NULL
#define transporter_Motion_timestamp_MSGTYPE transporter_Timestamp

#define transporter_MotionList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  motion,            1)
#define transporter_MotionList_CALLBACK pb_default_field_callback
#define transporter_MotionList_DEFAULT NULL
#define transporter_MotionList_motion_MSGTYPE transporter_Motion

#define transporter_LDR_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, DOUBLE,   ldr,               2) \
X(a, CALLBACK, SINGULAR, STRING,   port,              3)
#define transporter_LDR_CALLBACK pb_default_field_callback
#define transporter_LDR_DEFAULT NULL

#define transporter_LDRList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  ldr,               1)
#define transporter_LDRList_CALLBACK pb_default_field_callback
#define transporter_LDRList_DEFAULT NULL
#define transporter_LDRList_ldr_MSGTYPE transporter_LDR

#define transporter_SecurityRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, CALLBACK, SINGULAR, BYTES,    rfid,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         3)
#define transporter_SecurityRequest_CALLBACK pb_default_field_callback
#define transporter_SecurityRequest_DEFAULT NULL
#define transporter_SecurityRequest_timestamp_MSGTYPE transporter_Timestamp

#define transporter_SecurityResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, CALLBACK, SINGULAR, BYTES,    rfid,              2) \
X(a, STATIC,   SINGULAR, BOOL,     approved,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         4)
#define transporter_SecurityResponse_CALLBACK pb_default_field_callback
#define transporter_SecurityResponse_DEFAULT NULL
#define transporter_SecurityResponse_timestamp_MSGTYPE transporter_Timestamp

#define transporter_Config_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   name,              2) \
X(a, CALLBACK, SINGULAR, STRING,   description,       3) \
X(a, STATIC,   SINGULAR, UENUM,    device,            4) \
X(a, CALLBACK, SINGULAR, STRING,   port,              5) \
X(a, STATIC,   SINGULAR, INT32,    pin,               6) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         8)
#define transporter_Config_CALLBACK pb_default_field_callback
#define transporter_Config_DEFAULT NULL
#define transporter_Config_timestamp_MSGTYPE transporter_Timestamp

#define transporter_ConfigList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  config,            1)
#define transporter_ConfigList_CALLBACK pb_default_field_callback
#define transporter_ConfigList_DEFAULT NULL
#define transporter_ConfigList_config_MSGTYPE transporter_Config

extern const pb_msgdesc_t transporter_Timestamp_msg;
extern const pb_msgdesc_t transporter_Surrondings_msg;
extern const pb_msgdesc_t transporter_SurrondingsList_msg;
extern const pb_msgdesc_t transporter_Motion_msg;
extern const pb_msgdesc_t transporter_MotionList_msg;
extern const pb_msgdesc_t transporter_LDR_msg;
extern const pb_msgdesc_t transporter_LDRList_msg;
extern const pb_msgdesc_t transporter_SecurityRequest_msg;
extern const pb_msgdesc_t transporter_SecurityResponse_msg;
extern const pb_msgdesc_t transporter_Config_msg;
extern const pb_msgdesc_t transporter_ConfigList_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define transporter_Timestamp_fields &transporter_Timestamp_msg
#define transporter_Surrondings_fields &transporter_Surrondings_msg
#define transporter_SurrondingsList_fields &transporter_SurrondingsList_msg
#define transporter_Motion_fields &transporter_Motion_msg
#define transporter_MotionList_fields &transporter_MotionList_msg
#define transporter_LDR_fields &transporter_LDR_msg
#define transporter_LDRList_fields &transporter_LDRList_msg
#define transporter_SecurityRequest_fields &transporter_SecurityRequest_msg
#define transporter_SecurityResponse_fields &transporter_SecurityResponse_msg
#define transporter_Config_fields &transporter_Config_msg
#define transporter_ConfigList_fields &transporter_ConfigList_msg

/* Maximum encoded size of messages (where known) */
/* transporter_Surrondings_size depends on runtime parameters */
/* transporter_SurrondingsList_size depends on runtime parameters */
/* transporter_Motion_size depends on runtime parameters */
/* transporter_MotionList_size depends on runtime parameters */
/* transporter_LDR_size depends on runtime parameters */
/* transporter_LDRList_size depends on runtime parameters */
/* transporter_SecurityRequest_size depends on runtime parameters */
/* transporter_SecurityResponse_size depends on runtime parameters */
/* transporter_Config_size depends on runtime parameters */
/* transporter_ConfigList_size depends on runtime parameters */
#define TRANSPORTER_TRANSPORTER_PB_H_MAX_SIZE    transporter_Timestamp_size
#define transporter_Timestamp_size               22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
