/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "transporter.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(transporter_UID, transporter_UID, AUTO)


PB_BIND(transporter_RegisterRequest, transporter_RegisterRequest, AUTO)


PB_BIND(transporter_RegisterResponse, transporter_RegisterResponse, AUTO)


PB_BIND(transporter_RevokeRequest, transporter_RevokeRequest, AUTO)


PB_BIND(transporter_RfidEnvelope, transporter_RfidEnvelope, AUTO)


PB_BIND(transporter_Climate, transporter_Climate, AUTO)


PB_BIND(transporter_LDR, transporter_LDR, AUTO)


PB_BIND(transporter_Motion, transporter_Motion, AUTO)


PB_BIND(transporter_FullConfig, transporter_FullConfig, AUTO)


PB_BIND(transporter_ConfigTopic, transporter_ConfigTopic, AUTO)


PB_BIND(transporter_RelayState, transporter_RelayState, AUTO)


PB_BIND(transporter_ClimateData, transporter_ClimateData, AUTO)


PB_BIND(transporter_LDRData, transporter_LDRData, AUTO)







