/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TRANSPORTER_TRANSPORTER_PB_H_INCLUDED
#define PB_TRANSPORTER_TRANSPORTER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _transporter_RelayType {
    transporter_RelayType_UNKNOWN = 0,
    transporter_RelayType_LOW_DUTY = 1,
    transporter_RelayType_HEAVY_DUTY = 2
} transporter_RelayType;

typedef enum _transporter_RelayStateType {
    transporter_RelayStateType_OFF = 0,
    transporter_RelayStateType_ON = 1
} transporter_RelayStateType;

/* Struct definitions */
typedef struct _transporter_UID {
    pb_callback_t value;
} transporter_UID;

typedef struct _transporter_RegisterRequest {
    pb_callback_t id;
} transporter_RegisterRequest;

typedef struct _transporter_RegisterResponse {
    pb_callback_t id;
    bool has_uid;
    transporter_UID uid;
} transporter_RegisterResponse;

typedef struct _transporter_RevokeRequest {
    bool has_uid;
    transporter_UID uid;
} transporter_RevokeRequest;

typedef struct _transporter_RfidEnvelope {
    pb_callback_t cb_payload;
    pb_size_t which_payload;
    union {
        transporter_RegisterRequest register_request;
        transporter_RegisterResponse register_response;
        transporter_RevokeRequest revoke_request;
    } payload;
} transporter_RfidEnvelope;

typedef struct _transporter_Climate {
    uint32_t id;
    uint32_t dht22_port;
    uint32_t aqi_port;
    bool has_buzzers;
    uint32_t buzzer_port;
} transporter_Climate;

typedef struct _transporter_LDR {
    uint32_t id;
    uint32_t port;
} transporter_LDR;

typedef struct _transporter_Motion {
    uint32_t id;
    uint32_t port;
    uint32_t relay_port;
    transporter_RelayType relay_type;
} transporter_Motion;

typedef struct _transporter_FullConfig {
    pb_size_t climates_count;
    transporter_Climate climates[2];
    pb_size_t ldrs_count;
    transporter_LDR ldrs[2];
    pb_size_t motions_count;
    transporter_Motion motions[4];
} transporter_FullConfig;

typedef struct _transporter_ConfigTopic {
    pb_size_t which_payload;
    union {
        transporter_Climate climate;
        transporter_LDR ldr;
        transporter_Motion motion;
        transporter_FullConfig full_config;
    } payload;
} transporter_ConfigTopic;

typedef struct _transporter_RelayState {
    transporter_RelayType type;
    uint32_t port;
    transporter_RelayStateType state;
} transporter_RelayState;

typedef struct _transporter_ClimateData {
    uint32_t id;
    float temperature;
    float humidity;
    uint32_t aqi;
} transporter_ClimateData;

typedef struct _transporter_LDRData {
    uint32_t id;
    uint32_t value;
} transporter_LDRData;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _transporter_RelayType_MIN transporter_RelayType_UNKNOWN
#define _transporter_RelayType_MAX transporter_RelayType_HEAVY_DUTY
#define _transporter_RelayType_ARRAYSIZE ((transporter_RelayType)(transporter_RelayType_HEAVY_DUTY+1))

#define _transporter_RelayStateType_MIN transporter_RelayStateType_OFF
#define _transporter_RelayStateType_MAX transporter_RelayStateType_ON
#define _transporter_RelayStateType_ARRAYSIZE ((transporter_RelayStateType)(transporter_RelayStateType_ON+1))








#define transporter_Motion_relay_type_ENUMTYPE transporter_RelayType



#define transporter_RelayState_type_ENUMTYPE transporter_RelayType
#define transporter_RelayState_state_ENUMTYPE transporter_RelayStateType




/* Initializer values for message structs */
#define transporter_UID_init_default             {{{NULL}, NULL}}
#define transporter_RegisterRequest_init_default {{{NULL}, NULL}}
#define transporter_RegisterResponse_init_default {{{NULL}, NULL}, false, transporter_UID_init_default}
#define transporter_RevokeRequest_init_default   {false, transporter_UID_init_default}
#define transporter_RfidEnvelope_init_default    {{{NULL}, NULL}, 0, {transporter_RegisterRequest_init_default}}
#define transporter_Climate_init_default         {0, 0, 0, 0, 0}
#define transporter_LDR_init_default             {0, 0}
#define transporter_Motion_init_default          {0, 0, 0, _transporter_RelayType_MIN}
#define transporter_FullConfig_init_default      {0, {transporter_Climate_init_default, transporter_Climate_init_default}, 0, {transporter_LDR_init_default, transporter_LDR_init_default}, 0, {transporter_Motion_init_default, transporter_Motion_init_default, transporter_Motion_init_default, transporter_Motion_init_default}}
#define transporter_ConfigTopic_init_default     {0, {transporter_Climate_init_default}}
#define transporter_RelayState_init_default      {_transporter_RelayType_MIN, 0, _transporter_RelayStateType_MIN}
#define transporter_ClimateData_init_default     {0, 0, 0, 0}
#define transporter_LDRData_init_default         {0, 0}
#define transporter_UID_init_zero                {{{NULL}, NULL}}
#define transporter_RegisterRequest_init_zero    {{{NULL}, NULL}}
#define transporter_RegisterResponse_init_zero   {{{NULL}, NULL}, false, transporter_UID_init_zero}
#define transporter_RevokeRequest_init_zero      {false, transporter_UID_init_zero}
#define transporter_RfidEnvelope_init_zero       {{{NULL}, NULL}, 0, {transporter_RegisterRequest_init_zero}}
#define transporter_Climate_init_zero            {0, 0, 0, 0, 0}
#define transporter_LDR_init_zero                {0, 0}
#define transporter_Motion_init_zero             {0, 0, 0, _transporter_RelayType_MIN}
#define transporter_FullConfig_init_zero         {0, {transporter_Climate_init_zero, transporter_Climate_init_zero}, 0, {transporter_LDR_init_zero, transporter_LDR_init_zero}, 0, {transporter_Motion_init_zero, transporter_Motion_init_zero, transporter_Motion_init_zero, transporter_Motion_init_zero}}
#define transporter_ConfigTopic_init_zero        {0, {transporter_Climate_init_zero}}
#define transporter_RelayState_init_zero         {_transporter_RelayType_MIN, 0, _transporter_RelayStateType_MIN}
#define transporter_ClimateData_init_zero        {0, 0, 0, 0}
#define transporter_LDRData_init_zero            {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define transporter_UID_value_tag                1
#define transporter_RegisterRequest_id_tag       1
#define transporter_RegisterResponse_id_tag      1
#define transporter_RegisterResponse_uid_tag     2
#define transporter_RevokeRequest_uid_tag        1
#define transporter_RfidEnvelope_register_request_tag 3
#define transporter_RfidEnvelope_register_response_tag 4
#define transporter_RfidEnvelope_revoke_request_tag 5
#define transporter_Climate_id_tag               1
#define transporter_Climate_dht22_port_tag       2
#define transporter_Climate_aqi_port_tag         3
#define transporter_Climate_has_buzzers_tag      4
#define transporter_Climate_buzzer_port_tag      5
#define transporter_LDR_id_tag                   1
#define transporter_LDR_port_tag                 2
#define transporter_Motion_id_tag                1
#define transporter_Motion_port_tag              2
#define transporter_Motion_relay_port_tag        3
#define transporter_Motion_relay_type_tag        4
#define transporter_FullConfig_climates_tag      1
#define transporter_FullConfig_ldrs_tag          2
#define transporter_FullConfig_motions_tag       3
#define transporter_ConfigTopic_climate_tag      2
#define transporter_ConfigTopic_ldr_tag          3
#define transporter_ConfigTopic_motion_tag       4
#define transporter_ConfigTopic_full_config_tag  6
#define transporter_RelayState_type_tag          1
#define transporter_RelayState_port_tag          2
#define transporter_RelayState_state_tag         3
#define transporter_ClimateData_id_tag           1
#define transporter_ClimateData_temperature_tag  2
#define transporter_ClimateData_humidity_tag     3
#define transporter_ClimateData_aqi_tag          4
#define transporter_LDRData_id_tag               1
#define transporter_LDRData_value_tag            2

/* Struct field encoding specification for nanopb */
#define transporter_UID_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    value,             1)
#define transporter_UID_CALLBACK pb_default_field_callback
#define transporter_UID_DEFAULT NULL

#define transporter_RegisterRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1)
#define transporter_RegisterRequest_CALLBACK pb_default_field_callback
#define transporter_RegisterRequest_DEFAULT NULL

#define transporter_RegisterResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uid,               2)
#define transporter_RegisterResponse_CALLBACK pb_default_field_callback
#define transporter_RegisterResponse_DEFAULT NULL
#define transporter_RegisterResponse_uid_MSGTYPE transporter_UID

#define transporter_RevokeRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  uid,               1)
#define transporter_RevokeRequest_CALLBACK NULL
#define transporter_RevokeRequest_DEFAULT NULL
#define transporter_RevokeRequest_uid_MSGTYPE transporter_UID

#define transporter_RfidEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,register_request,payload.register_request),   3) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,register_response,payload.register_response),   4) \
X(a, STATIC,   ONEOF,    MSG_W_CB, (payload,revoke_request,payload.revoke_request),   5)
#define transporter_RfidEnvelope_CALLBACK NULL
#define transporter_RfidEnvelope_DEFAULT NULL
#define transporter_RfidEnvelope_payload_register_request_MSGTYPE transporter_RegisterRequest
#define transporter_RfidEnvelope_payload_register_response_MSGTYPE transporter_RegisterResponse
#define transporter_RfidEnvelope_payload_revoke_request_MSGTYPE transporter_RevokeRequest

#define transporter_Climate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   dht22_port,        2) \
X(a, STATIC,   SINGULAR, UINT32,   aqi_port,          3) \
X(a, STATIC,   SINGULAR, BOOL,     has_buzzers,       4) \
X(a, STATIC,   SINGULAR, UINT32,   buzzer_port,       5)
#define transporter_Climate_CALLBACK NULL
#define transporter_Climate_DEFAULT NULL

#define transporter_LDR_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   port,              2)
#define transporter_LDR_CALLBACK NULL
#define transporter_LDR_DEFAULT NULL

#define transporter_Motion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   port,              2) \
X(a, STATIC,   SINGULAR, UINT32,   relay_port,        3) \
X(a, STATIC,   SINGULAR, UENUM,    relay_type,        4)
#define transporter_Motion_CALLBACK NULL
#define transporter_Motion_DEFAULT NULL

#define transporter_FullConfig_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  climates,          1) \
X(a, STATIC,   REPEATED, MESSAGE,  ldrs,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  motions,           3)
#define transporter_FullConfig_CALLBACK NULL
#define transporter_FullConfig_DEFAULT NULL
#define transporter_FullConfig_climates_MSGTYPE transporter_Climate
#define transporter_FullConfig_ldrs_MSGTYPE transporter_LDR
#define transporter_FullConfig_motions_MSGTYPE transporter_Motion

#define transporter_ConfigTopic_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,climate,payload.climate),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ldr,payload.ldr),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,motion,payload.motion),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,full_config,payload.full_config),   6)
#define transporter_ConfigTopic_CALLBACK NULL
#define transporter_ConfigTopic_DEFAULT NULL
#define transporter_ConfigTopic_payload_climate_MSGTYPE transporter_Climate
#define transporter_ConfigTopic_payload_ldr_MSGTYPE transporter_LDR
#define transporter_ConfigTopic_payload_motion_MSGTYPE transporter_Motion
#define transporter_ConfigTopic_payload_full_config_MSGTYPE transporter_FullConfig

#define transporter_RelayState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   port,              2) \
X(a, STATIC,   SINGULAR, UENUM,    state,             3)
#define transporter_RelayState_CALLBACK NULL
#define transporter_RelayState_DEFAULT NULL

#define transporter_ClimateData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          3) \
X(a, STATIC,   SINGULAR, UINT32,   aqi,               4)
#define transporter_ClimateData_CALLBACK NULL
#define transporter_ClimateData_DEFAULT NULL

#define transporter_LDRData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2)
#define transporter_LDRData_CALLBACK NULL
#define transporter_LDRData_DEFAULT NULL

extern const pb_msgdesc_t transporter_UID_msg;
extern const pb_msgdesc_t transporter_RegisterRequest_msg;
extern const pb_msgdesc_t transporter_RegisterResponse_msg;
extern const pb_msgdesc_t transporter_RevokeRequest_msg;
extern const pb_msgdesc_t transporter_RfidEnvelope_msg;
extern const pb_msgdesc_t transporter_Climate_msg;
extern const pb_msgdesc_t transporter_LDR_msg;
extern const pb_msgdesc_t transporter_Motion_msg;
extern const pb_msgdesc_t transporter_FullConfig_msg;
extern const pb_msgdesc_t transporter_ConfigTopic_msg;
extern const pb_msgdesc_t transporter_RelayState_msg;
extern const pb_msgdesc_t transporter_ClimateData_msg;
extern const pb_msgdesc_t transporter_LDRData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define transporter_UID_fields &transporter_UID_msg
#define transporter_RegisterRequest_fields &transporter_RegisterRequest_msg
#define transporter_RegisterResponse_fields &transporter_RegisterResponse_msg
#define transporter_RevokeRequest_fields &transporter_RevokeRequest_msg
#define transporter_RfidEnvelope_fields &transporter_RfidEnvelope_msg
#define transporter_Climate_fields &transporter_Climate_msg
#define transporter_LDR_fields &transporter_LDR_msg
#define transporter_Motion_fields &transporter_Motion_msg
#define transporter_FullConfig_fields &transporter_FullConfig_msg
#define transporter_ConfigTopic_fields &transporter_ConfigTopic_msg
#define transporter_RelayState_fields &transporter_RelayState_msg
#define transporter_ClimateData_fields &transporter_ClimateData_msg
#define transporter_LDRData_fields &transporter_LDRData_msg

/* Maximum encoded size of messages (where known) */
/* transporter_UID_size depends on runtime parameters */
/* transporter_RegisterRequest_size depends on runtime parameters */
/* transporter_RegisterResponse_size depends on runtime parameters */
/* transporter_RevokeRequest_size depends on runtime parameters */
/* transporter_RfidEnvelope_size depends on runtime parameters */
#define TRANSPORTER_TRANSPORTER_PB_H_MAX_SIZE    transporter_ConfigTopic_size
#define transporter_ClimateData_size             22
#define transporter_Climate_size                 26
#define transporter_ConfigTopic_size             175
#define transporter_FullConfig_size              172
#define transporter_LDRData_size                 12
#define transporter_LDR_size                     12
#define transporter_Motion_size                  20
#define transporter_RelayState_size              10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
