/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(config_Climate, config_Climate, AUTO)


PB_BIND(config_LDR, config_LDR, AUTO)


PB_BIND(config_Motion, config_Motion, AUTO)


PB_BIND(config_Relay, config_Relay, AUTO)


PB_BIND(config_Config, config_Config, AUTO)





